name: Residence Deployment 🚀

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy on VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        command_timeout: 120s
        timeout: 120s
        script: |
          cd /var/www/ResidenceMeubl-

          git fetch origin main
          git reset --hard origin/main

          cd client
          npm install --legacy-peer-deps
          npm run build
          cp -r public/images dist/images

          rm -rf /var/www/residences/*
          cp -r dist/* /var/www/residences/

          cd ../backend
          npm install --production

          rm -rf /var/www/residences-api/*
          cp -r . /var/www/residences-api/

          cd /var/www/residences-api
          pm2 restart residences-api || pm2 start server.js --name residences-api
          pm2 save